CREATE TABLE `blueprints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`format` enum('reel','carousel','image') NOT NULL,
	`description` text,
	`hookType` varchar(128),
	`structure` text,
	`pacing` varchar(128),
	`length` varchar(64),
	`audioStrategy` text,
	`visualStyle` text,
	`ctaStrategy` text,
	`usageCount` int DEFAULT 0,
	`score` int DEFAULT 0,
	`sourcePostId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blueprints_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `creators` (
	`id` int AUTO_INCREMENT NOT NULL,
	`handle` varchar(128) NOT NULL,
	`platform` varchar(32) NOT NULL DEFAULT 'instagram',
	`niche` varchar(128),
	`followerCount` int NOT NULL DEFAULT 0,
	`weeklyGrowthRate` float DEFAULT 0,
	`postingFrequency` float DEFAULT 0,
	`averageViews` int DEFAULT 0,
	`engagementRate` float DEFAULT 0,
	`bio` text,
	`impactScore` int DEFAULT 0,
	`topFormat` varchar(32),
	`avatarUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creators_id` PRIMARY KEY(`id`),
	CONSTRAINT `creators_handle_unique` UNIQUE(`handle`)
);
--> statement-breakpoint
CREATE TABLE `posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`url` text,
	`creatorId` int NOT NULL,
	`creatorHandle` varchar(128) NOT NULL,
	`title` varchar(512) NOT NULL,
	`format` enum('reel','carousel','image') NOT NULL,
	`niche` varchar(128),
	`views` int NOT NULL DEFAULT 0,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`engagementRate` float DEFAULT 0,
	`followerCountAtPosting` int DEFAULT 0,
	`caption` text,
	`hashtags` text,
	`impactScore` int DEFAULT 0,
	`hookType` varchar(128),
	`contentStructure` text,
	`pacing` varchar(128),
	`length` varchar(64),
	`audioStrategy` text,
	`visualStyle` text,
	`ctaStrategy` text,
	`thumbnailUrl` text,
	`postedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `posts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `userProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instagramHandle` varchar(128) NOT NULL,
	`followerCount` int DEFAULT 0,
	`weeklyGrowthRate` float DEFAULT 0,
	`postingFrequency` float DEFAULT 0,
	`averageViews` int DEFAULT 0,
	`engagementRate` float DEFAULT 0,
	`bio` text,
	`impactScore` int DEFAULT 0,
	`topFormat` varchar(32),
	`niche` varchar(128),
	`diagnostics` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `userProfiles_id` PRIMARY KEY(`id`)
);
